package com.dyq.bletest.model.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dyq.bletest.model.database.HrInfo;

import com.dyq.bletest.model.database.HrInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hrInfoDaoConfig;

    private final HrInfoDao hrInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hrInfoDaoConfig = daoConfigMap.get(HrInfoDao.class).clone();
        hrInfoDaoConfig.initIdentityScope(type);

        hrInfoDao = new HrInfoDao(hrInfoDaoConfig, this);

        registerDao(HrInfo.class, hrInfoDao);
    }
    
    public void clear() {
        hrInfoDaoConfig.getIdentityScope().clear();
    }

    public HrInfoDao getHrInfoDao() {
        return hrInfoDao;
    }

}
